universe = docker
docker_image = fodinabor/llvm-dev:18
executable = run.bash
output = synth_$(Cluster).out
error = synth_$(Cluster).err
log = synth_$(Cluster).log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
getenv = HOME, PWD
environment = SUBMIT_PWD=$ENV(PWD)
request_CPUs = 64
request_memory = 1000GB
request_GPUs = 0
requirements = UidDomain == "cs.uni-saarland.de"
accounting_group = chair_cdl
+WantGPUHomeMounted = true

queue

